"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Carro_1 = require("./Carro");
var Moto_1 = require("./Moto");
var carro = new Carro_1.default("Civic", "Preto", 4);
var moto = new Moto_1.default("CG Titã", "Vermelha");
moto.acelerar();
carro.acelerar();
console.log(carro.velocidadeAtual());
console.log(moto.velocidadeAtual());
